# -*- coding: utf-8 -*-
"""untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/gist/AlexandraSP96/638c53a4066dba3ac96ef4204c789fd2/untitled0.ipynb

# íniciar o Python

Este é o meu primeiro trabalho em **Python**

primeiro comando , imprimir a frase " Olá! Seja bem vindo à minha página"
"""

print("Olá! Seja bem vindo à minha página")

"""Vou importar a biblioteca mais utilizada na base de dados"""

import pandas as pd

"""Vou importar um excel
1º Tive que passar o ficheiro para a aba da esquerda
2º Executar o comando com o caminho entre aspas
"""

pd.read_excel("/content/controle_da_empresa.xlsx")

"""No primeiro comando não foram importadas todas as abas"""

planilha=pd.read_excel("/content/controle_da_empresa.xlsx", None)

"""Vamos executar a variável criada , que é a planilha"""

planilha

"""Quero ver uma aba específica (maiusculas e minusculas são consideradas)"""

planilha ["Estoque"]

"""Quero ver outra aba"""

planilha ["Vendas"]

"""E se eu não souber o nome de todas as abas do excel?"""

planilha.keys()

"""quero só uma coluna"""

planilha ["Vendas"] ["Total de Vendas"]

"""Quero somar essas colunas"""

planilha ["Vendas"] ["Total de Vendas"].sum()

"""Calcular a média"""

planilha ["Vendas"] ["Total de Vendas"].mean()

"""Calcular a mediana"""

planilha ["Vendas"] ["Total de Vendas"].median()

"""Calcular o desvio padrão"""

planilha ["Vendas"] ["Total de Vendas"].std()

"""Criar uma variàvel para não estar sempre a escrever planilha["Vendas"]"""

vendas = planilha ["Vendas"]

vendas

"""Criar um gráfico de linhas"""

vendas.plot ("Data da Venda", "Total de Vendas")

"""Criar um Histograma"""

vendas.hist("Total de Vendas")